import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
async function main() {
  console.log("=== Seeding speaking topics ===");
  const topics = [
    { part: 1, topic: "Work and Study", questions: JSON.stringify(["Do you work or are you a student?", "What do you like most about your job/studies?", "What would be your ideal job?"]), modelAnswer: "I am currently a university student majoring in Business Administration. What I enjoy most about my studies is the opportunity to learn about different aspects of business management..." },
    { part: 1, topic: "Hometown", questions: JSON.stringify(["Where is your hometown?", "What do you like about your hometown?", "Has your hometown changed much since you were a child?"]), modelAnswer: "My hometown is a small city in the southern part of China called Guangzhou. What I love most about it is the warm climate and the delicious local cuisine..." },
    { part: 1, topic: "Hobbies", questions: JSON.stringify(["What do you do in your free time?", "How long have you been doing this hobby?", "Do you prefer to spend free time alone or with others?"]), modelAnswer: "In my free time, I enjoy reading books and playing basketball. Reading helps me relax and learn new things, while basketball keeps me fit..." },
    { part: 1, topic: "Food and Cooking", questions: JSON.stringify(["What kind of food do you like?", "Do you prefer eating at home or eating out?", "Have you ever tried cooking a new cuisine?"]), modelAnswer: "I enjoy a wide variety of foods, but my favorite is Chinese cuisine, especially Sichuan dishes. I generally prefer eating at home because it is more economical and healthier..." },
    { part: 1, topic: "Travel", questions: JSON.stringify(["Do you like traveling?", "What is the best place you have visited?", "Where would you like to travel in the future?"]), modelAnswer: "Yes, I am passionate about traveling. The best place I have visited so far is Japan, where I was amazed by the blend of traditional culture and modern technology..." },
    { part: 1, topic: "Technology", questions: JSON.stringify(["How often do you use the internet?", "What do you use technology for most?", "Do you think technology has changed the way people communicate?"]), modelAnswer: "I use the internet every day for various purposes, including studying, working, and staying connected with friends. Technology has dramatically changed communication by making it instant..." },
    { part: 2, topic: "Describe a person you admire", questions: JSON.stringify(["Who is this person?", "How do you know them?", "What qualities do they have?", "Explain why you admire them"]), modelAnswer: "The person I admire most is my high school history teacher, Mr. Zhang. I first met him when I was 15 years old, and he completely changed my perspective on learning..." },
    { part: 2, topic: "Describe a place you enjoyed visiting", questions: JSON.stringify(["Where is this place?", "When did you visit it?", "What did you do there?", "Explain why you enjoyed it"]), modelAnswer: "One place that left a lasting impression on me is the Great Wall of China. I visited it during a school trip when I was 16 years old..." },
    { part: 2, topic: "Describe a skill you learned recently", questions: JSON.stringify(["What skill did you learn?", "How did you learn it?", "Was it difficult to learn?", "How has this skill been useful?"]), modelAnswer: "Recently, I learned how to play the acoustic guitar. I started learning during the summer break by watching online tutorials and practicing for about an hour every day..." },
    { part: 3, topic: "Education and Learning", questions: JSON.stringify(["How has education changed in your country?", "What is the importance of lifelong learning?", "Should education be free for everyone?"]), modelAnswer: "Education in China has undergone significant changes over the past few decades. There has been a shift from traditional rote learning toward more interactive and critical thinking-based approaches..." },
    { part: 3, topic: "Technology and Society", questions: JSON.stringify(["How has technology affected people social lives?", "What are the disadvantages of social media?", "Will technology continue to replace human jobs?"]), modelAnswer: "Technology has had both positive and negative effects on social lives. While it has made communication more convenient, it has also reduced face-to-face interaction..." },
    { part: 3, topic: "Environment and Sustainability", questions: JSON.stringify(["What are the main environmental problems in your country?", "What can individuals do to protect the environment?", "Should governments do more to tackle climate change?"]), modelAnswer: "The main environmental issues in my country include air pollution, water contamination, and waste management. Individuals can make a difference by reducing waste, conserving energy, and using public transportation..." },
  ];
  for (const t of topics) {
    await prisma.speakingTopic.upsert({ where: { id: t.part + "-" + t.topic.substring(0, 20) }, update: t, create: { ...t, id: t.part + "-" + t.topic.substring(0, 20) } });
  }
  const c = await prisma.speakingTopic.count();
  console.log("Speaking topics: " + c);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
